services:
  viz-dev:
    image: viz-dev:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    pull_policy: missing
    container_name: viz-dev-container
    environment:
      - HOSTNAME=viz-dev-container
    volumes:
      - .:/app
      - dependencies:/opt/dependencies
    working_dir: /app
    tty: true
    stdin_open: true

volumes:
  dependencies:
    name: viz-dependencies
